#!/bin/bash
set -e -u -x

mkdir -p $GOPATH/src/github.com/shinji62/concourse-meetup-goserv/
cp -R concourse-meetup-goserv-ci/*  $GOPATH/src/github.com/shinji62/concourse-meetup-goserv/
cd $GOPATH/src/github.com/shinji62/concourse-meetup-goserv/
go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega
make test