#!/bin/bash
set -e -u -x
export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd $GOPATH/src/github.com/shinji62/concourse-meetup-goserv/

go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega
make test