#!/bin/bash
set -e -u -x
export ROOT_DIR=$PWD
export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd $GOPATH/src/github.com/shinji62/concourse-meetup-goserv/

make clean
make compile

mv dist ${ROOT_DIR}/concourse-meetup-goserv-ci-build/
